<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jonhonjump</artifactId>
        <groupId>cn.jonhon.jump.boot</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>jonhonjump-module-mall</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>

    <description>
        商城大模块，由 product 商品、promotion 营销、trade 交易、statistics 统计等组成
    </description>
    <modules>
        <module>jonhonjump-module-product</module>
        <module>jonhonjump-module-promotion</module>
        <module>jonhonjump-module-trade</module>
        <module>jonhonjump-module-statistics</module>
        <!--
            特殊：为什么会有 jonhonjump-module-trade-api 呢？
                jonhonjump-module-promotion 和 jonhonjump-module-trade 之间相互循环依赖，所以抽出 jonhonjump-module-trade-api 模块，这样：
                1. jonhonjump-module-promotion 依赖 jonhonjump-module-trade-api
                2. jonhonjump-module-trade 依赖 jonhonjump-module-promotion
            从而不存在相互（循环）依赖，即 jonhonjump-module-trade => jonhonjump-module-promotion => jonhonjump-module-trade-api
         -->
        <module>jonhonjump-module-trade-api</module>
    </modules>

</project>
