-- =============================================================================
-- Camstar MES：4200 车间人员 / 角色 / 菜单
--
-- 人员表 EMPLOYEE 没有 FACTORYID。现网新增人员 workshopCode 必填、teamCode 可选，
-- 所以「只走班组」会少人。正确口径是下面几条的并集去重：
--
--   1) 班组     TEAMEMPLOYEE → TEAM.FACTORYID
--   2) 会话车间 EMPLOYEE.SESSIONVALUESID → SESSIONVALUES.FACTORYID
--               （人员管理按车间查询走这条，没班组的人也在这里）
--   3) 默认产线 EMPLOYEE.PRODUCTLINEID → PRODUCTLINE.FACTORYID
--   4) 默认工位 EMPLOYEE.WORKCENTERID → WORKCENTER → PRODUCTLINE
--   5) 主组织   EMPLOYEE.PRIMARYORGANIZATIONID = 车间ID/组织ID
--
-- 4200 也不一定等于 FACTORY.FACTORYNAME，可能在 DEPT_WORKSHOP / 部门 OA_NO。
-- 先跑 A，确认解析出几个车间、各路径人数。
-- =============================================================================

-- 改这一处即可（Navicat / PLSQL 都能跑，不用 DEFINE）
-- =============================================================================
-- A. 解析 4200 对应哪些车间 + 各路径人数
-- =============================================================================
WITH p AS (
    SELECT '4200' AS workshop_code FROM dual
),
factory_hit AS (
    SELECT f.FACTORYID, f.FACTORYNAME, f.DESCRIPTION, f.DEPARTMENTID, f.ORGANIZATIONID, 'FACTORYNAME' AS hit
    FROM FACTORY f, p
    WHERE TRIM(f.FACTORYNAME) = p.workshop_code
       OR TRIM(f.FACTORYNAME) LIKE p.workshop_code || '%'
    UNION
    SELECT f.FACTORYID, f.FACTORYNAME, f.DESCRIPTION, f.DEPARTMENTID, f.ORGANIZATIONID, 'DEPT_WORKSHOP'
    FROM DEPT_WORKSHOP dw, p, FACTORY f
    WHERE TRIM(dw.WORKSHOP_CODE) = p.workshop_code
      AND (TRIM(f.FACTORYNAME) = TRIM(dw.WORKSHOP_CODE)
        OR TRIM(f.DEPARTMENTID) = TRIM(dw.DEPT_ID))
    UNION
    SELECT f.FACTORYID, f.FACTORYNAME, f.DESCRIPTION, f.DEPARTMENTID, f.ORGANIZATIONID, 'DEPT_OA'
    FROM DEPARTMENT d, p, FACTORY f
    WHERE (TRIM(d.OA_NO) = p.workshop_code OR TRIM(d.DEPARTMENTNAME) = p.workshop_code)
      AND f.DEPARTMENTID = d.DEPARTMENTID
    UNION
    -- IS_UNION_BY_DEPT=是：同部门其它车间也算进来
    SELECT f2.FACTORYID, f2.FACTORYNAME, f2.DESCRIPTION, f2.DEPARTMENTID, f2.ORGANIZATIONID, 'UNION_BY_DEPT'
    FROM DEPT_WORKSHOP dw, p, FACTORY f1, FACTORY f2
    WHERE TRIM(dw.WORKSHOP_CODE) = p.workshop_code
      AND NVL(dw.IS_UNION_BY_DEPT, '否') IN ('是', 'Y', '1', 'YES', 'yes')
      AND TRIM(f1.FACTORYNAME) = TRIM(dw.WORKSHOP_CODE)
      AND f2.DEPARTMENTID = f1.DEPARTMENTID
)
SELECT hit, TRIM(FACTORYID) AS factory_id, FACTORYNAME, DESCRIPTION
FROM factory_hit
ORDER BY hit, FACTORYNAME;


-- A2. 各路径人数（看少在哪条）
WITH p AS (
    SELECT '4200' AS workshop_code FROM dual
),
factory_hit AS (
    SELECT f.FACTORYID, f.ORGANIZATIONID
    FROM FACTORY f, p
    WHERE TRIM(f.FACTORYNAME) = p.workshop_code
       OR TRIM(f.FACTORYNAME) LIKE p.workshop_code || '%'
    UNION
    SELECT f.FACTORYID, f.ORGANIZATIONID
    FROM DEPT_WORKSHOP dw, p, FACTORY f
    WHERE TRIM(dw.WORKSHOP_CODE) = p.workshop_code
      AND (TRIM(f.FACTORYNAME) = TRIM(dw.WORKSHOP_CODE)
        OR TRIM(f.DEPARTMENTID) = TRIM(dw.DEPT_ID))
    UNION
    SELECT f.FACTORYID, f.ORGANIZATIONID
    FROM DEPARTMENT d, p, FACTORY f
    WHERE (TRIM(d.OA_NO) = p.workshop_code OR TRIM(d.DEPARTMENTNAME) = p.workshop_code)
      AND f.DEPARTMENTID = d.DEPARTMENTID
    UNION
    SELECT f2.FACTORYID, f2.ORGANIZATIONID
    FROM DEPT_WORKSHOP dw, p, FACTORY f1, FACTORY f2
    WHERE TRIM(dw.WORKSHOP_CODE) = p.workshop_code
      AND NVL(dw.IS_UNION_BY_DEPT, '否') IN ('是', 'Y', '1', 'YES', 'yes')
      AND TRIM(f1.FACTORYNAME) = TRIM(dw.WORKSHOP_CODE)
      AND f2.DEPARTMENTID = f1.DEPARTMENTID
)
SELECT '1-班组' AS path, COUNT(DISTINCT te.EMPLOYEEID) AS emp_cnt
FROM TEAMEMPLOYEE te
JOIN TEAM t ON t.TEAMID = te.TEAMID
JOIN factory_hit f ON f.FACTORYID = t.FACTORYID
UNION ALL
SELECT '1c-班组经产线(TEAM.PRODUCTLINEID弃用字段)', COUNT(DISTINCT te.EMPLOYEEID)
FROM TEAMEMPLOYEE te
JOIN TEAM t ON t.TEAMID = te.TEAMID
JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = t.PRODUCTLINEID
JOIN factory_hit f ON f.FACTORYID = pl.FACTORYID
UNION ALL
SELECT '2-SESSION会话车间', COUNT(DISTINCT NVL(e.EMPLOYEEID, sv.EMPLOYEEID))
FROM SESSIONVALUES sv
JOIN factory_hit f ON f.FACTORYID = sv.FACTORYID
LEFT JOIN EMPLOYEE e ON e.SESSIONVALUESID = sv.SESSIONVALUESID
UNION ALL
SELECT '3-默认产线', COUNT(DISTINCT e.EMPLOYEEID)
FROM EMPLOYEE e
JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = e.PRODUCTLINEID
JOIN factory_hit f ON f.FACTORYID = pl.FACTORYID
UNION ALL
SELECT '4-默认工位', COUNT(DISTINCT e.EMPLOYEEID)
FROM EMPLOYEE e
JOIN WORKCENTER wc ON wc.WORKCENTERID = e.WORKCENTERID
JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = wc.PRODUCTLINEID
JOIN factory_hit f ON f.FACTORYID = pl.FACTORYID
UNION ALL
SELECT '5-主组织PRIMARYORGANIZATIONID', COUNT(DISTINCT e.EMPLOYEEID)
FROM EMPLOYEE e
JOIN factory_hit f
  ON e.PRIMARYORGANIZATIONID = f.FACTORYID
  OR e.PRIMARYORGANIZATIONID = f.ORGANIZATIONID
UNION ALL
SELECT '并集去重(1~5,导出用这个人数)', COUNT(DISTINCT employee_id)
FROM (
    SELECT te.EMPLOYEEID AS employee_id
    FROM TEAMEMPLOYEE te
    JOIN TEAM t ON t.TEAMID = te.TEAMID
    JOIN factory_hit f ON f.FACTORYID = t.FACTORYID
    UNION
    SELECT te.EMPLOYEEID
    FROM TEAMEMPLOYEE te
    JOIN TEAM t ON t.TEAMID = te.TEAMID
    JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = t.PRODUCTLINEID
    JOIN factory_hit f ON f.FACTORYID = pl.FACTORYID
    UNION
    SELECT NVL(e.EMPLOYEEID, sv.EMPLOYEEID)
    FROM SESSIONVALUES sv
    JOIN factory_hit f ON f.FACTORYID = sv.FACTORYID
    LEFT JOIN EMPLOYEE e ON e.SESSIONVALUESID = sv.SESSIONVALUESID
    UNION
    SELECT e.EMPLOYEEID
    FROM EMPLOYEE e
    JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = e.PRODUCTLINEID
    JOIN factory_hit f ON f.FACTORYID = pl.FACTORYID
    UNION
    SELECT e.EMPLOYEEID
    FROM EMPLOYEE e
    JOIN WORKCENTER wc ON wc.WORKCENTERID = e.WORKCENTERID
    JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = wc.PRODUCTLINEID
    JOIN factory_hit f ON f.FACTORYID = pl.FACTORYID
    UNION
    SELECT e.EMPLOYEEID
    FROM EMPLOYEE e
    JOIN factory_hit f
      ON e.PRIMARYORGANIZATIONID = f.FACTORYID
      OR e.PRIMARYORGANIZATIONID = f.ORGANIZATIONID
);


-- =============================================================================
-- B. 导出人员（班组 ∪ 会话车间 ∪ 默认产线/工位 ∪ 主组织，一人一行）
-- =============================================================================
WITH p AS (
    SELECT '4200' AS workshop_code FROM dual
),
factory_hit AS (
    SELECT f.FACTORYID, f.FACTORYNAME, f.DESCRIPTION, f.ORGANIZATIONID
    FROM FACTORY f, p
    WHERE TRIM(f.FACTORYNAME) = p.workshop_code
       OR TRIM(f.FACTORYNAME) LIKE p.workshop_code || '%'
    UNION
    SELECT f.FACTORYID, f.FACTORYNAME, f.DESCRIPTION, f.ORGANIZATIONID
    FROM DEPT_WORKSHOP dw, p, FACTORY f
    WHERE TRIM(dw.WORKSHOP_CODE) = p.workshop_code
      AND (TRIM(f.FACTORYNAME) = TRIM(dw.WORKSHOP_CODE)
        OR TRIM(f.DEPARTMENTID) = TRIM(dw.DEPT_ID))
    UNION
    SELECT f.FACTORYID, f.FACTORYNAME, f.DESCRIPTION, f.ORGANIZATIONID
    FROM DEPARTMENT d, p, FACTORY f
    WHERE (TRIM(d.OA_NO) = p.workshop_code OR TRIM(d.DEPARTMENTNAME) = p.workshop_code)
      AND f.DEPARTMENTID = d.DEPARTMENTID
    UNION
    SELECT f2.FACTORYID, f2.FACTORYNAME, f2.DESCRIPTION, f2.ORGANIZATIONID
    FROM DEPT_WORKSHOP dw, p, FACTORY f1, FACTORY f2
    WHERE TRIM(dw.WORKSHOP_CODE) = p.workshop_code
      AND NVL(dw.IS_UNION_BY_DEPT, '否') IN ('是', 'Y', '1', 'YES', 'yes')
      AND TRIM(f1.FACTORYNAME) = TRIM(dw.WORKSHOP_CODE)
      AND f2.DEPARTMENTID = f1.DEPARTMENTID
),
emp_ids AS (
    SELECT te.EMPLOYEEID AS employee_id
    FROM TEAMEMPLOYEE te
    JOIN TEAM t ON t.TEAMID = te.TEAMID
    JOIN factory_hit f ON f.FACTORYID = t.FACTORYID
    UNION
    SELECT te.EMPLOYEEID
    FROM TEAMEMPLOYEE te
    JOIN TEAM t ON t.TEAMID = te.TEAMID
    JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = t.PRODUCTLINEID
    JOIN factory_hit f ON f.FACTORYID = pl.FACTORYID
    UNION
    SELECT NVL(e.EMPLOYEEID, sv.EMPLOYEEID)
    FROM SESSIONVALUES sv
    JOIN factory_hit f ON f.FACTORYID = sv.FACTORYID
    LEFT JOIN EMPLOYEE e ON e.SESSIONVALUESID = sv.SESSIONVALUESID
    UNION
    SELECT e.EMPLOYEEID
    FROM EMPLOYEE e
    JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = e.PRODUCTLINEID
    JOIN factory_hit f ON f.FACTORYID = pl.FACTORYID
    UNION
    SELECT e.EMPLOYEEID
    FROM EMPLOYEE e
    JOIN WORKCENTER wc ON wc.WORKCENTERID = e.WORKCENTERID
    JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = wc.PRODUCTLINEID
    JOIN factory_hit f ON f.FACTORYID = pl.FACTORYID
    UNION
    SELECT e.EMPLOYEEID
    FROM EMPLOYEE e
    JOIN factory_hit f
      ON e.PRIMARYORGANIZATIONID = f.FACTORYID
      OR e.PRIMARYORGANIZATIONID = f.ORGANIZATIONID
)
SELECT
    TRIM(e.EMPLOYEEID)     AS employee_id,
    e.EMPLOYEEUSERNAME     AS employee_code,
    e.FULLNAME             AS full_name,
    e.ERPNO                AS erp_no,
    e.CARDNO               AS card_no,
    e.DOCMANAGERUSER       AS domain_user,
    e.DOMAINNAME           AS domain_name,
    e.EMAILADDRESS         AS email,
    e.JOBNAME              AS job_name,
    e.WORKLICENSE          AS work_license,
    e.CANLOGIN             AS can_login,
    e.ISONDUTY             AS is_on_duty,
    e.ISFROZEN             AS is_frozen,
    TRIM(sv.FACTORYID)     AS session_factory_id,
    sf.FACTORYNAME         AS session_factory_code,
    TRIM(e.PRODUCTLINEID)  AS productline_id,
    pl.PRODUCTLINENAME     AS productline_code,
    TRIM(e.WORKCENTERID)   AS workcenter_id,
    wc.WORKCENTERNAME      AS workcenter_code,
    TRIM(e.MENUDEFINITIONID)               AS menu_definition_id,
    TRIM(e.PORTALMENUDEFINITIONID)         AS portal_menu_id,
    TRIM(e.PORTALMOBILEMENUDEFINITIONID)   AS portal_mobile_menu_id,
    TRIM(e.WEBMENUDEFINITIONID)            AS web_menu_id,
    TRIM(e.WEBDWILLDOWNERMENUDEFINITIONID) AS web_dw_menu_id,
    e.PORTALHOMEPAGE                       AS portal_home_page,
    TRIM(e.UIPORTALPROFILEID)              AS ui_portal_profile_id
FROM EMPLOYEE e
JOIN emp_ids ids ON ids.employee_id = e.EMPLOYEEID
LEFT JOIN SESSIONVALUES sv ON sv.SESSIONVALUESID = e.SESSIONVALUESID
LEFT JOIN FACTORY sf ON sf.FACTORYID = sv.FACTORYID
LEFT JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = e.PRODUCTLINEID
LEFT JOIN WORKCENTER wc ON wc.WORKCENTERID = e.WORKCENTERID
ORDER BY e.EMPLOYEEUSERNAME;


-- =============================================================================
-- C. 人员角色
-- =============================================================================
WITH p AS (
    SELECT '4200' AS workshop_code FROM dual
),
factory_hit AS (
    SELECT f.FACTORYID, f.ORGANIZATIONID
    FROM FACTORY f, p
    WHERE TRIM(f.FACTORYNAME) = p.workshop_code
       OR TRIM(f.FACTORYNAME) LIKE p.workshop_code || '%'
    UNION
    SELECT f.FACTORYID, f.ORGANIZATIONID
    FROM DEPT_WORKSHOP dw, p, FACTORY f
    WHERE TRIM(dw.WORKSHOP_CODE) = p.workshop_code
      AND (TRIM(f.FACTORYNAME) = TRIM(dw.WORKSHOP_CODE)
        OR TRIM(f.DEPARTMENTID) = TRIM(dw.DEPT_ID))
    UNION
    SELECT f.FACTORYID, f.ORGANIZATIONID
    FROM DEPARTMENT d, p, FACTORY f
    WHERE (TRIM(d.OA_NO) = p.workshop_code OR TRIM(d.DEPARTMENTNAME) = p.workshop_code)
      AND f.DEPARTMENTID = d.DEPARTMENTID
    UNION
    SELECT f2.FACTORYID, f2.ORGANIZATIONID
    FROM DEPT_WORKSHOP dw, p, FACTORY f1, FACTORY f2
    WHERE TRIM(dw.WORKSHOP_CODE) = p.workshop_code
      AND NVL(dw.IS_UNION_BY_DEPT, '否') IN ('是', 'Y', '1', 'YES', 'yes')
      AND TRIM(f1.FACTORYNAME) = TRIM(dw.WORKSHOP_CODE)
      AND f2.DEPARTMENTID = f1.DEPARTMENTID
),
emp_ids AS (
    SELECT te.EMPLOYEEID AS employee_id
    FROM TEAMEMPLOYEE te
    JOIN TEAM t ON t.TEAMID = te.TEAMID
    JOIN factory_hit f ON f.FACTORYID = t.FACTORYID
    UNION
    SELECT NVL(e.EMPLOYEEID, sv.EMPLOYEEID)
    FROM SESSIONVALUES sv
    JOIN factory_hit f ON f.FACTORYID = sv.FACTORYID
    LEFT JOIN EMPLOYEE e ON e.SESSIONVALUESID = sv.SESSIONVALUESID
    UNION
    SELECT e.EMPLOYEEID
    FROM EMPLOYEE e
    JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = e.PRODUCTLINEID
    JOIN factory_hit f ON f.FACTORYID = pl.FACTORYID
    UNION
    SELECT e.EMPLOYEEID
    FROM EMPLOYEE e
    JOIN WORKCENTER wc ON wc.WORKCENTERID = e.WORKCENTERID
    JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = wc.PRODUCTLINEID
    JOIN factory_hit f ON f.FACTORYID = pl.FACTORYID
    UNION
    SELECT e.EMPLOYEEID
    FROM EMPLOYEE e
    JOIN factory_hit f
      ON e.PRIMARYORGANIZATIONID = f.FACTORYID
      OR e.PRIMARYORGANIZATIONID = f.ORGANIZATIONID
)
SELECT DISTINCT
    e.EMPLOYEEUSERNAME      AS employee_code,
    e.FULLNAME              AS full_name,
    TRIM(er.EMPLOYEEROLEID) AS employee_role_id,
    TRIM(r.ROLEID)          AS role_id,
    r.ROLENAME              AS role_code,
    r.ROLETYPE              AS role_type,
    r.DESCRIPTION           AS role_desc,
    r.NOTES                 AS role_notes,
    TRIM(er.ORGANIZATIONID) AS role_org_id
FROM EMPLOYEE e
JOIN emp_ids ids ON ids.employee_id = e.EMPLOYEEID
JOIN EMPLOYEEROLE er ON er.EMPLOYEEID = e.EMPLOYEEID
LEFT JOIN ROLEDEF r ON r.ROLEID = er.ROLEID
ORDER BY e.EMPLOYEEUSERNAME, r.ROLENAME;

-- 角色定义：NOTES 里写车间编码（Camstar 人员管理接口常用）
SELECT TRIM(ROLEID) AS role_id, ROLENAME, ROLETYPE, DESCRIPTION, NOTES, ISFROZEN
FROM ROLEDEF
WHERE TRIM(NOTES) = '4200'
   OR NOTES LIKE '4200%'
ORDER BY ROLENAME;


-- =============================================================================
-- D. 人员菜单
-- =============================================================================
WITH p AS (
    SELECT '4200' AS workshop_code FROM dual
),
factory_hit AS (
    SELECT f.FACTORYID, f.ORGANIZATIONID
    FROM FACTORY f, p
    WHERE TRIM(f.FACTORYNAME) = p.workshop_code
       OR TRIM(f.FACTORYNAME) LIKE p.workshop_code || '%'
    UNION
    SELECT f.FACTORYID, f.ORGANIZATIONID
    FROM DEPT_WORKSHOP dw, p, FACTORY f
    WHERE TRIM(dw.WORKSHOP_CODE) = p.workshop_code
      AND (TRIM(f.FACTORYNAME) = TRIM(dw.WORKSHOP_CODE)
        OR TRIM(f.DEPARTMENTID) = TRIM(dw.DEPT_ID))
    UNION
    SELECT f.FACTORYID, f.ORGANIZATIONID
    FROM DEPARTMENT d, p, FACTORY f
    WHERE (TRIM(d.OA_NO) = p.workshop_code OR TRIM(d.DEPARTMENTNAME) = p.workshop_code)
      AND f.DEPARTMENTID = d.DEPARTMENTID
    UNION
    SELECT f2.FACTORYID, f2.ORGANIZATIONID
    FROM DEPT_WORKSHOP dw, p, FACTORY f1, FACTORY f2
    WHERE TRIM(dw.WORKSHOP_CODE) = p.workshop_code
      AND NVL(dw.IS_UNION_BY_DEPT, '否') IN ('是', 'Y', '1', 'YES', 'yes')
      AND TRIM(f1.FACTORYNAME) = TRIM(dw.WORKSHOP_CODE)
      AND f2.DEPARTMENTID = f1.DEPARTMENTID
),
emp_ids AS (
    SELECT te.EMPLOYEEID AS employee_id
    FROM TEAMEMPLOYEE te
    JOIN TEAM t ON t.TEAMID = te.TEAMID
    JOIN factory_hit f ON f.FACTORYID = t.FACTORYID
    UNION
    SELECT NVL(e.EMPLOYEEID, sv.EMPLOYEEID)
    FROM SESSIONVALUES sv
    JOIN factory_hit f ON f.FACTORYID = sv.FACTORYID
    LEFT JOIN EMPLOYEE e ON e.SESSIONVALUESID = sv.SESSIONVALUESID
    UNION
    SELECT e.EMPLOYEEID
    FROM EMPLOYEE e
    JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = e.PRODUCTLINEID
    JOIN factory_hit f ON f.FACTORYID = pl.FACTORYID
    UNION
    SELECT e.EMPLOYEEID
    FROM EMPLOYEE e
    JOIN WORKCENTER wc ON wc.WORKCENTERID = e.WORKCENTERID
    JOIN PRODUCTLINE pl ON pl.PRODUCTLINEID = wc.PRODUCTLINEID
    JOIN factory_hit f ON f.FACTORYID = pl.FACTORYID
    UNION
    SELECT e.EMPLOYEEID
    FROM EMPLOYEE e
    JOIN factory_hit f
      ON e.PRIMARYORGANIZATIONID = f.FACTORYID
      OR e.PRIMARYORGANIZATIONID = f.ORGANIZATIONID
)
SELECT DISTINCT
    e.EMPLOYEEUSERNAME                     AS employee_code,
    e.FULLNAME                             AS full_name,
    TRIM(e.MENUDEFINITIONID)               AS menu_definition_id,
    TRIM(e.PORTALMENUDEFINITIONID)         AS portal_menu_id,
    TRIM(e.PORTALMOBILEMENUDEFINITIONID)   AS portal_mobile_menu_id,
    TRIM(e.WEBMENUDEFINITIONID)            AS web_menu_id,
    TRIM(e.WEBDWILLDOWNERMENUDEFINITIONID) AS web_dw_menu_id,
    e.PORTALHOMEPAGE                       AS portal_home_page,
    TRIM(e.UIPORTALPROFILEID)              AS ui_portal_profile_id,
    up.MASTERPAGE                          AS portal_master_page,
    TRIM(up.PORTALHOMEPAGEID)              AS portal_home_page_id,
    up.THEME                               AS portal_theme
FROM EMPLOYEE e
JOIN emp_ids ids ON ids.employee_id = e.EMPLOYEEID
LEFT JOIN UIPORTALPROFILE up ON up.UIPORTALPROFILEID = e.UIPORTALPROFILEID
ORDER BY e.EMPLOYEEUSERNAME;


-- =============================================================================
-- E. 4200 角色 ↔ 菜单（依据 doc/批量数据处理.docx）
--
-- 关系不是人员表上的 MENUDEFINITIONID，而是：
--   ROLEDEF.ROLENAME 形如 4200_xxx
--     → ROLEPERMISSION (ROLEID + ROLEPERMISSIONNAME)
--     → UIVIRTUALPAGE.UIVIRTUALPAGENAME = ROLEPERMISSIONNAME
--     → PORTALMENUITEM.VIRTUALPAGEID
--     → PORTALMENUDEFINITION / 上级 PORTALMENUITEM
--
-- 车间过滤：ROLENAME LIKE '4200_%'
-- URL：Portal Studio 批量导出 all.xml 解析进 VP_URL_DESC 后才能拼上
-- =============================================================================

-- E1. 4200 角色
SELECT
    TRIM(ROLEID) AS role_id,
    ROLENAME     AS role_code,
    ROLETYPE,
    DESCRIPTION,
    NOTES,
    ISFROZEN
FROM ROLEDEF
WHERE ROLENAME LIKE '4200_%'
  AND ROLENAME NOT LIKE 'Default%'
ORDER BY ROLENAME;

-- E2. 角色-虚拟页权限（最核心的角色菜单关系）
SELECT
    rd.ROLENAME              AS role_code,
    SUBSTR(rd.ROLENAME, 1, INSTR(rd.ROLENAME, '_') - 1) AS workshop_code,
    rp.ROLEPERMISSIONNAME    AS vp_name,
    ui.UIVIRTUALPAGENAME,
    ui.SUBMENUNAME,
    ui.TEMPLATEPAGE
FROM ROLEPERMISSION rp
JOIN ROLEDEF rd ON rd.ROLEID = rp.ROLEID
LEFT JOIN UIVIRTUALPAGE ui ON ui.UIVIRTUALPAGENAME = rp.ROLEPERMISSIONNAME
WHERE rd.ROLENAME LIKE '4200_%'
  AND rd.ROLENAME NOT LIKE 'Default%'
ORDER BY rd.ROLENAME, rp.ROLEPERMISSIONNAME;

-- E3. 角色-菜单树（一级门户菜单 + 菜单项标题 + VP）
SELECT DISTINCT
    rd.ROLENAME                     AS role_code,
    SUBSTR(rd.ROLENAME, 1, INSTR(rd.ROLENAME, '_') - 1) AS workshop_code,
    pmf.PORTALMENUDEFINITIONNAME    AS portal_menu_name,
    pm.CAPTION                      AS menu_caption,
    pm.SEQUENCE                     AS menu_seq,
    rp.ROLEPERMISSIONNAME           AS vp_name
FROM UIVIRTUALPAGE ui
JOIN ROLEPERMISSION rp ON ui.UIVIRTUALPAGENAME = rp.ROLEPERMISSIONNAME
JOIN ROLEDEF rd ON rd.ROLEID = rp.ROLEID
JOIN PORTALMENUITEM pm ON pm.VIRTUALPAGEID = ui.UIVIRTUALPAGEID
JOIN PORTALMENUDEFINITION pmf ON pm.PARENTID = pmf.PORTALMENUDEFINITIONID
WHERE rd.ROLENAME LIKE '4200_%'
  AND rd.ROLENAME NOT LIKE 'Default%'
ORDER BY rd.ROLENAME, pmf.PORTALMENUDEFINITIONNAME, pm.SEQUENCE, pm.CAPTION;

-- E4. 4200 角色用到的一级菜单（去重）
SELECT DISTINCT pmf.PORTALMENUDEFINITIONNAME AS portal_menu_name
FROM UIVIRTUALPAGE ui
JOIN ROLEPERMISSION rp ON ui.UIVIRTUALPAGENAME = rp.ROLEPERMISSIONNAME
JOIN ROLEDEF rd ON rd.ROLEID = rp.ROLEID
JOIN PORTALMENUITEM pm ON pm.VIRTUALPAGEID = ui.UIVIRTUALPAGEID
JOIN PORTALMENUDEFINITION pmf ON pm.PARENTID = pmf.PORTALMENUDEFINITIONID
WHERE rd.ROLENAME LIKE '4200_%'
  AND rd.ROLENAME NOT LIKE 'Default%'
ORDER BY pmf.PORTALMENUDEFINITIONNAME;

-- E5. 若已按文档把 all.xml 解析进 VP_URL_DESC，拼 URL
-- SELECT DISTINCT
--     rd.ROLENAME,
--     pmf.PORTALMENUDEFINITIONNAME,
--     pm.CAPTION,
--     rp.ROLEPERMISSIONNAME,
--     CASE WHEN vud.URL IS NOT NULL THEN vud.URL ELSE vud.DESCRIPTION END AS url
-- FROM UIVIRTUALPAGE ui
-- JOIN ROLEPERMISSION rp ON ui.UIVIRTUALPAGENAME = rp.ROLEPERMISSIONNAME
-- JOIN ROLEDEF rd ON rd.ROLEID = rp.ROLEID
-- JOIN PORTALMENUITEM pm ON pm.VIRTUALPAGEID = ui.UIVIRTUALPAGEID
-- JOIN PORTALMENUDEFINITION pmf ON pm.PARENTID = pmf.PORTALMENUDEFINITIONID
-- JOIN VP_URL_DESC vud ON vud.NAME = rp.ROLEPERMISSIONNAME
-- WHERE rd.ROLENAME LIKE '4200_%'
--   AND rd.ROLENAME NOT LIKE 'Default%'
-- ORDER BY rd.ROLENAME, pmf.PORTALMENUDEFINITIONNAME, pm.CAPTION;

-- E6. 若 4200 有独立「全功能菜单」，先查出菜单定义名
SELECT PORTALMENUDEFINITIONID, PORTALMENUDEFINITIONNAME
FROM PORTALMENUDEFINITION
WHERE PORTALMENUDEFINITIONNAME LIKE '%4200%'
   OR PORTALMENUDEFINITIONNAME LIKE '%全功能%'
ORDER BY PORTALMENUDEFINITIONNAME;
