-- =============================================================================
-- Oracle MESDB1：把 XML 补充菜单插入 D2_SYS_MENU
-- 来源：docs/MESDB1_D2_SYS_MENU.xlsx  sheet「XML补充菜单」
-- 可重复执行：已存在同 MENU_ID 则跳过
-- =============================================================================

-- 11263 排产引擎参数配置 (d2_aps_engineConfig)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11263, '排产引擎参数配置', 2001, 105,
  'http://192.168.240.127:4221/aps/engineConfig/index', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_aps_engineConfig',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11263);

-- 11264 产品全周期标准数据 (d2_aps_productCycle)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11264, '产品全周期标准数据', 2001, 110,
  'http://192.168.240.127:4221/aps/productCycle/index', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_aps_productCycle',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11264);

-- 11265 超期订单查询 (d2_ExceedOrderIndex)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11265, '超期订单查询', 2001, 115,
  'http://192.168.240.127:4200/WorkOrder/OrderManager/ExceedOrderIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_ExceedOrderIndex',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11265);

-- 11266 工单解限审批 (d2_lantai_keeponfilenew)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11266, '工单解限审批', 2001, 120,
  'http://192.168.240.127:4221/d2/lantai/keeponfilenew', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_lantai_keeponfilenew',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11266);

-- 11267 待拣选工单导入 (d2_PickTaskImport)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11267, '待拣选工单导入', 2001, 125,
  'https://192.168.240.127:4200/Base//FunctionalArea/ImportUnpickWorkOrderIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_PickTaskImport',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11267);

-- 11268 在制品工单详情 (d2_workorder_detail)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11268, '在制品工单详情', 2001, 130,
  'http://192.168.240.127:4221/workorder/manage/detail', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_workorder_detail',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11268);

-- 11269 在制品工单管理 (d2_workorder_manage)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11269, '在制品工单管理', 2001, 135,
  'http://192.168.240.127:4221/workorder/manage', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_workorder_manage',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11269);

-- 11270 应聘人页面 (d2_applicantIndex_vp)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11270, '应聘人页面', 2002, 160,
  'http://192.168.240.127:4221/innovation/applicantIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_applicantIndex_vp',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11270);

-- 11271 辅材维护页面 (d2_auxiliary_vp)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11271, '辅材维护页面', 2002, 165,
  'http://192.168.240.127:4221/auxiliary/index', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_auxiliary_vp',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11271);

-- 11272 辅材领用申请页面 (d2_auxiliaryApply_vp)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11272, '辅材领用申请页面', 2002, 170,
  'http://192.168.240.127:4221/auxiliary/applyIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_auxiliaryApply_vp',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11272);

-- 11273 辅材领用管理员页面 (d2_auxiliaryCustodian_vp)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11273, '辅材领用管理员页面', 2002, 175,
  'http://192.168.240.127:4221/auxiliary/custodianIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_auxiliaryCustodian_vp',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11273);

-- 11274 班组人员接收详情 (d2_BzzWorkOrderReceive)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11274, '班组人员接收详情', 2002, 180,
  'http://192.168.240.127:4200/ProExecute/ProExecuteManager/BzzWorkorderReceive', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_BzzWorkOrderReceive',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11274);

-- 11275 物流线在制订单查询 (d2_LogisExcute_vp)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11275, '物流线在制订单查询', 2002, 185,
  'http://192.168.240.127:4200/ProExecute/ProExecuteManager/LogtisticsInExcuteIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_LogisExcute_vp',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11275);

-- 11276 打字班/裁线班发料页面 (d2_MaterialIssuance)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11276, '打字班/裁线班发料页面', 2002, 190,
  'http://192.168.240.127:4200/ProExecute/ProExecuteManager/MaterialIssuanceIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_MaterialIssuance',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11276);

-- 11277 在制订单查询 (d2_OrderInProcess)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11277, '在制订单查询', 2002, 195,
  'http://192.168.240.127:4200/ProExecute/ProExecuteManager/OrderInProcess', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_OrderInProcess',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11277);

-- 11278 问题处理 (d2_ProblemHandle)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11278, '问题处理', 2002, 200,
  'http://192.168.240.127:4200/base/problembasicData/ProblemHandleIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_ProblemHandle',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11278);

-- 11279 问题提交 (d2_ProblemSubmit)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11279, '问题提交', 2002, 205,
  'http://192.168.240.127:4200/base/problembasicData/ProblemsubmitIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_ProblemSubmit',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11279);

-- 11280 招聘人页面 (d2_recruiterIndex_vp)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11280, '招聘人页面', 2002, 210,
  'http://192.168.240.127:4221/innovation/recruiterIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_recruiterIndex_vp',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11280);

-- 11281 排产计划 (d2_workorderinfo)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11281, '排产计划', 2002, 215,
  'http://192.168.240.127:4200/ProExecute/SubmitWorkManager/WorkOrderInfo', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_workorderinfo',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11281);

-- 11282 装配班组物料齐套 (d2_WorkOrderKitting_vp)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11282, '装配班组物料齐套', 2002, 220,
  'http://192.168.240.127:4200/ProExecute/ProExecuteManager/WorkOrderKittingIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_WorkOrderKitting_vp',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11282);

-- 11283 工艺能力信息维护 (d2_ex_functeam)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11283, '工艺能力信息维护', 2003, 105,
  'http://192.168.240.127:4221/process/ex/functeam', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_ex_functeam',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11283);

-- 11284 无工艺产品页面 (d2_NoProcess)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11284, '无工艺产品页面', 2003, 110,
  'http://192.168.240.127:4200/Process/ProcessManager/NoProcess', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_NoProcess',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11284);

-- 11285 工艺工序错误页面 (d2_ProcessProcedureError)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11285, '工艺工序错误页面', 2003, 115,
  'http://192.168.240.127:4200/Process/ProcessManager/ProcessProcedureError', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_ProcessProcedureError',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11285);

-- 11286 工艺派工页面 (d2_ProcessSendJob)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11286, '工艺派工页面', 2003, 120,
  'http://192.168.240.127:4200/Process/ProcessManager/ProcessSendJob', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_ProcessSendJob',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11286);

-- 11287 工艺版本错误页面 (d2_ProcessVersionError)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11287, '工艺版本错误页面', 2003, 125,
  'http://192.168.240.127:4200/Process/ProcessManager/ProcessVersionError', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_ProcessVersionError',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11287);

-- 11288 投影布线文件上传 (d2_touying_fileuplod)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11288, '投影布线文件上传', 2003, 130,
  'http://192.168.240.127:4221/procss/touying/fileupload', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_touying_fileuplod',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11288);

-- 11289 工作订单页面 (d2_WoNoIndex)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11289, '工作订单页面', 2003, 135,
  'http://192.168.240.127:4200/Process/ProcessManager/WoIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_WoNoIndex',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11289);

-- 11290 工序与检测项关联 (d2_Operationitemlinkindex)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11290, '工序与检测项关联', 2004, 85,
  'http://192.168.240.127:4200/Base/testitemBasicData/Operationitemlinkindex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_Operationitemlinkindex',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11290);

-- 11291 班组拣选任务 (d2_ConfirmPickTaskOut)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11291, '班组拣选任务', 2005, 250,
  'https://192.168.240.127:4200/Base/FunctionalArea/TaskGroupByTeam', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_ConfirmPickTaskOut',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11291);

-- 11292 裁线人员对应班组若依版 (d2_CroperForTeamRuoYiIndex)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11292, '裁线人员对应班组若依版', 2005, 255,
  'http://192.168.240.127:4221/assemblyteam/index', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_CroperForTeamRuoYiIndex',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11292);

-- 11293 字典管理 (d2_DictionaryIndex)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11293, '字典管理', 2005, 260,
  'http://192.168.240.124:9011/Common/Dictionary/DictionaryIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_DictionaryIndex',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11293);

-- 11294 物料确认 (d2_MaterialConfirm)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11294, '物料确认', 2005, 265,
  'http://192.168.240.127:4200/base/MaterialConfirm/MaterialConfirm', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_MaterialConfirm',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11294);

-- 11295 复合胶配制 (d2_MultGlueConfect)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11295, '复合胶配制', 2005, 270,
  'http://192.168.240.124:9011/multiglue/multigluelist', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_MultGlueConfect',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11295);

-- 11296 复合胶维护 (d2_MultGlueList)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11296, '复合胶维护', 2005, 275,
  'http://192.168.240.124:9011/multiglue/multigluelist/MultiGlueMaintenance', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_MultGlueList',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11296);

-- 11297 每日上线率看板 (d2_dayMesRateBoard)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11297, '每日上线率看板', 2007, 175,
  'http://192.168.240.127:4221/orderManger/mesOnlineRate/dayMesRateBoard', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_dayMesRateBoard',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11297);

-- 11298 异常订单未处理看板 (d2_ErrorWorkOrderUnHandleTimeBoard)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11298, '异常订单未处理看板', 2007, 180,
  'http://192.168.240.127:4200/SealReport/MPOProductQuality/ErrorWorkOrderUnHandleTimeBoard', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_ErrorWorkOrderUnHandleTimeBoard',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11298);

-- 11299 非标工艺看板 (d2_NonStandardProcessBoard)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11299, '非标工艺看板', 2007, 185,
  'http://192.168.240.127:4200/sealreport/bulletinBoard/NonStandardProcessBoard', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_NonStandardProcessBoard',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11299);

-- 11300 二部上线率报表 (d2_OnLineRateBoard)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11300, '二部上线率报表', 2007, 190,
  'http://192.168.240.127:4200/SealReport/MPOProductQuality/OnLineRateBoard', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_OnLineRateBoard',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11300);

-- 11301 二部功能区滞留时间看板 (d2_RetentionTimeBoard)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11301, '二部功能区滞留时间看板', 2007, 195,
  'http://192.168.240.127:4200/SealReport/MPOProductQuality/RetenrionTimeBoard', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_RetentionTimeBoard',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11301);

-- 11302 班组创建工单异常看板 (d2_TeamCreateWorkAbnormalBoard)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11302, '班组创建工单异常看板', 2007, 200,
  'http://192.168.240.127:4200/SealReport/MPOProductQuality/TeamCreateWorkAbnormalBoard', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_TeamCreateWorkAbnormalBoard',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11302);

-- 11303 待处理问题看板 (d2_unHandleBoard_vp)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11303, '待处理问题看板', 2007, 205,
  'http://192.168.240.127:4221/unHandleBoard/index', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_unHandleBoard_vp',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11303);

-- 11304 每周上线率看板 (d2_weekMesRateBoard)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11304, '每周上线率看板', 2007, 210,
  'http://192.168.240.127:4221/orderManger/mesOnlineRate/weekMesRateBoard', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_weekMesRateBoard',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11304);

-- 11305 工时复核审批评审 (d2_process_workHourReviewIndex)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11305, '工时复核审批评审', 2008, 15,
  'http://192.168.240.127:4221/procss/workHourReview/index', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_process_workHourReviewIndex',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11305);

-- 11306 功能区料盒监控 (d2_AreaBoxMonitor)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11306, '功能区料盒监控', 2010, 100,
  'http://192.168.240.127:4200/MaterialFlow/StoreIssue/AreaBoxMonitor', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_AreaBoxMonitor',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11306);

-- 11307 库位和料盒信息展示 (D2_BoxInfo)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11307, '库位和料盒信息展示', 2010, 105,
  'http://192.168.240.127:4200/materialflow/warehousearea/warehouseboxinfo', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'D2_BoxInfo',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11307);

-- 11308 人员工位基础信息维护 (d2_EmployeeWorkCenterJobView)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11308, '人员工位基础信息维护', 2010, 110,
  'http://192.168.240.127:4200/MaterialFlow/StoreIssue/EmployeeWorkCenterJobView', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_EmployeeWorkCenterJobView',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11308);

-- 11309 试验线流转任务监控 (d2_MoveTaskMonitor)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11309, '试验线流转任务监控', 2010, 115,
  'http://192.168.240.127:4200/MaterialFlow/StoreIssue/MoveTaskMonitor', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_MoveTaskMonitor',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11309);

-- 11310 库管员发料 (d2_StoreIssue)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11310, '库管员发料', 2010, 120,
  'http://192.168.240.127:4200/MaterialFlow/StoreIssue/StoreIssue', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_StoreIssue',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11310);

-- 11311 库管员发料(新) (d2_StoreIssue_New)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11311, '库管员发料(新)', 2010, 125,
  'http://192.168.240.127:4200/MaterialFlow/StoreIssue/MaterialOutStore', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_StoreIssue_New',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11311);

-- 11312 连接器装配班货架详情 (D2_TypingClassShelfInfo)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11312, '连接器装配班货架详情', 2010, 130,
  'http://192.168.240.127:4200/materialflow/warehousearea/typingclassshelfinfo', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'D2_TypingClassShelfInfo',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11312);

-- 11313 空料盒解绑记录 (d2_UnTieBox)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11313, '空料盒解绑记录', 2010, 135,
  'http://192.168.240.127:4200/MaterialFlow/StoreIssue/UnTieBoxRecord', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_UnTieBox',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11313);

-- 11314 库区管理 (d2_WarehouseAreaManageIndex)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11314, '库区管理', 2010, 140,
  'http://192.168.240.127:4200/MaterialFlow/warehousearea/WarehouseAreaManageIndex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_WarehouseAreaManageIndex',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11314);

-- 11315 工单生产进度跟踪 (D2_WorkorderProSchedule)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11315, '工单生产进度跟踪', 2010, 145,
  'http://192.168.240.127:4200/materialflow/storeissue/workorderproschedule', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'D2_WorkorderProSchedule',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11315);

-- 11316 工装基础信息 (d2_ToolsBasicInfo)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11316, '工装基础信息', 2012, 75,
  'http://192.168.240.13:9071/tools/toolbasicinfo/toolbasicinfoindex', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_ToolsBasicInfo',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11316);

-- 11317 工装借用信息(新) (tool_borrow_new)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11317, '工装借用信息(新)', 2013, 265,
  'http://192.168.240.123:8080/tool/borrowinfo/new', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'tool_borrow_new',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11317);

-- 11318 工装料盒入库 (tool_box_inbound)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11318, '工装料盒入库', 2013, 270,
  'http://192.168.240.123:8080/tool/box/inbound', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'tool_box_inbound',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11318);

-- 11319 工装柜维护 (tool_cabinet)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11319, '工装柜维护', 2013, 275,
  'http://192.168.240.123:8080/tool/cabinet', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'tool_cabinet',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11319);

-- 11320 工装分类维护 (tool_classify)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11320, '工装分类维护', 2013, 280,
  'http://192.168.240.123:8080/tool/baseinfo/classify', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'tool_classify',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11320);

-- 11321 工装入库工作台 (tool_inbound_workbench)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11321, '工装入库工作台', 2013, 285,
  'http://192.168.240.123:8080/tool/inbound/Workbench', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'tool_inbound_workbench',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11321);

-- 11322 工装拣选工作台 (tool_picking_Workbench)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11322, '工装拣选工作台', 2013, 290,
  'http://192.168.240.123:8080/tool/picking/Workbench', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'tool_picking_Workbench',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11322);

-- 11323 工装转入 (tool_transfer-in)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11323, '工装转入', 2013, 295,
  'http://192.168.240.123:8080/tool/transfer-in', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'tool_transfer-in',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11323);

-- 11324 工装转出 (tool_transfer-out)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11324, '工装转出', 2013, 300,
  'http://192.168.240.123:8080/tool/transfer-out', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'tool_transfer-out',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11324);

-- 11325 工装货架货格 (tool_ware_shelfgrid)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11325, '工装货架货格', 2013, 305,
  'http://192.168.240.123:8080/tool/ware/shelfgrid', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'tool_ware_shelfgrid',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11325);

-- 11326 测试页面 (d2_ruoyitest_vp)
INSERT INTO D2_SYS_MENU (
  MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
  IS_FRAME, IS_CACHE, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON, REMARK,
  CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT
  11326, '测试页面', 0, 70,
  'http://192.168.240.127:4221/test', NULL, NULL,
  '1', '0', 'C',
  '0', '0',
  NULL, '#', 'd2_ruoyitest_vp',
  'admin', SYSDATE, 'admin', SYSDATE
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM D2_SYS_MENU WHERE MENU_ID = 11326);

COMMIT;

SELECT COUNT(*) AS xml_supplement_menus FROM D2_SYS_MENU WHERE MENU_ID BETWEEN 11263 AND 11326;
